export const GET_ALL_TEACHERS_REQUEST =  "GET_ALL_TEACHERS_REQUEST"
export const GET_ALL_TEACHERS_SUCCESS =  "GET_ALL_TEACHERS_SUCCESS"
export const GET_ALL_TEACHERS_FAIL =  "GET_ALL_TEACHERS_FAIL"
export const GET_ALL_TEACHERS_RESET =  "GET_ALL_TEACHERS_RESET"

export const GET_ALL_SUBJECTS_REQUEST =  "GET_ALL_SUBJECTS_REQUEST"
export const GET_ALL_SUBJECTS_SUCCESS =  "GET_ALL_SUBJECTS_SUCCESS"
export const GET_ALL_SUBJECTS_FAIL =  "GET_ALL_SUBJECTS_FAIL"
export const GET_ALL_SUBJECTS_RESET =  "GET_ALL_SUBJECTS_RESET"

export const GET_ALL_DEPARTMENTS_REQUEST =  "GET_ALL_DEPARTMENTS_REQUEST"
export const GET_ALL_DEPARTMENTS_SUCCESS =  "GET_ALL_DEPARTMENTS_SUCCESS"
export const GET_ALL_DEPARTMENTS_FAIL =  "GET_ALL_DEPARTMENTS_FAIL"
export const GET_ALL_DEPARTMENTS_RESET =  "GET_ALL_DEPARTMENTS_RESET"

export const GET_ALL_CLASSES_REQUEST =  "GET_ALL_CLASSES_REQUEST"
export const GET_ALL_CLASSES_SUCCESS =  "GET_ALL_CLASSES_SUCCESS"
export const GET_ALL_CLASSES_FAIL =  "GET_ALL_CLASSES_FAIL"
export const GET_ALL_CLASSES_RESET =  "GET_ALL_CLASSES_RESET"

export const GET_ALL_POST_REQUEST =  "GET_ALL_POST_REQUEST"
export const GET_ALL_POST_SUCCESS =  "GET_ALL_POST_SUCCESS"
export const GET_ALL_POST_FAIL =  "GET_ALL_POST_FAIL"
export const GET_ALL_POST_RESET =  "GET_ALL_POST_RESET"

export const ADMIN_GET_ALL_TEACHERS_REQUEST =  "ADMIN_GET_ALL_TEACHERS_REQUEST"
export const ADMIN_GET_ALL_TEACHERS_SUCCESS =  "ADMIN_GET_ALL_TEACHERS_SUCCESS"
export const ADMIN_GET_ALL_TEACHERS_FAIL =  "ADMIN_GET_ALL_TEACHERS_FAIL"
export const ADMIN_GET_ALL_TEACHERS_RESET =  "ADMIN_GET_ALL_TEACHERS_RESET"

export const ADMIN_GET_ALL_PARENTS_REQUEST =  "ADMIN_GET_ALL_PARENTS_REQUEST"
export const ADMIN_GET_ALL_PARENTS_SUCCESS =  "ADMIN_GET_ALL_PARENTS_SUCCESS"
export const ADMIN_GET_ALL_PARENTS_FAIL =  "ADMIN_GET_ALL_PARENTS_FAIL"
export const ADMIN_GET_ALL_PARENTS_RESET =  "ADMIN_GET_ALL_PARENTS_RESET"

export const ADMIN_GET_ALL_STUDENTS_REQUEST =  "ADMIN_GET_ALL_STUDENTS_REQUEST"
export const ADMIN_GET_ALL_STUDENTS_SUCCESS =  "ADMIN_GET_ALL_STUDENTS_SUCCESS"
export const ADMIN_GET_ALL_STUDENTS_FAIL =  "ADMIN_GET_ALL_STUDENTS_FAIL"
export const ADMIN_GET_ALL_STUDENTS_RESET =  "ADMIN_GET_ALL_STUDENTS_RESET"

export const SEARCH_TEACHERS_REQUEST =  "SEARCH_TEACHERS_REQUEST"
export const SEARCH_TEACHERS_SUCCESS =  "SEARCH_TEACHERS_SUCCESS"
export const SEARCH_TEACHERS_FAIL =  "SEARCH_TEACHERS_FAIL"
export const SEARCH_TEACHERS_RESET =  "SEARCH_TEACHERS_RESET"

export const ADMIN_SEARCH_TEACHERS_REQUEST =  "ADMIN_SEARCH_TEACHERS_REQUEST"
export const ADMIN_SEARCH_TEACHERS_SUCCESS =  "ADMIN_SEARCH_TEACHERS_SUCCESS"
export const ADMIN_SEARCH_TEACHERS_FAIL =  "ADMIN_SEARCH_TEACHERS_FAIL"
export const ADMIN_SEARCH_TEACHERS_RESET =  "ADMIN_SEARCH_TEACHERS_RESET"

export const ADMIN_SEARCH_PARENTS_REQUEST =  "ADMIN_SEARCH_PARENTS_REQUEST"
export const ADMIN_SEARCH_PARENTS_SUCCESS =  "ADMIN_SEARCH_PARENTS_SUCCESS"
export const ADMIN_SEARCH_PARENTS_FAIL =  "ADMIN_SEARCH_PARENTS_FAIL"
export const ADMIN_SEARCH_PARENTS_RESET =  "ADMIN_SEARCH_PARENTS_RESET"

export const ADMIN_SEARCH_STUDENTS_REQUEST =  "ADMIN_SEARCH_STUDENTS_REQUEST"
export const ADMIN_SEARCH_STUDENTS_SUCCESS =  "ADMIN_SEARCH_STUDENTS_SUCCESS"
export const ADMIN_SEARCH_STUDENTS_FAIL =  "ADMIN_SEARCH_STUDENTS_FAIL"
export const ADMIN_SEARCH_STUDENTS_RESET =  "ADMIN_SEARCH_STUDENTS_RESET"

export const ADMIN_SEARCH_NEWS_REQUEST =  "ADMIN_SEARCH_NEWS_REQUEST"
export const ADMIN_SEARCH_NEWS_SUCCESS =  "ADMIN_SEARCH_NEWS_SUCCESS"
export const ADMIN_SEARCH_NEWS_FAIL =  "ADMIN_SEARCH_NEWS_FAIL"
export const ADMIN_SEARCH_NEWS_RESET =  "ADMIN_SEARCH_NEWS_RESET"

export const SEARCH_CALENDAR_REQUEST =  "SEARCH_CALENDAR_REQUEST"
export const SEARCH_CALENDAR_SUCCESS =  "SEARCH_CALENDAR_SUCCESS"
export const SEARCH_CALENDAR_FAIL =  "SEARCH_CALENDAR_FAIL"
export const SEARCH_CALENDAR_RESET =  "SEARCH_CALENDAR_RESET"

export const ADMIN_SEARCH_IMAGES_REQUEST =  "ADMIN_SEARCH_IMAGES_REQUEST"
export const ADMIN_SEARCH_IMAGES_SUCCESS =  "ADMIN_SEARCH_IMAGES_SUCCESS"
export const ADMIN_SEARCH_IMAGES_FAIL =  "ADMIN_SEARCH_IMAGES_FAIL"
export const ADMIN_SEARCH_IMAGES_RESET =  "ADMIN_SEARCH_IMAGES_RESET"

export const GET_ALL_NEWS_REQUEST =  "GET_ALL_NEWS_REQUEST"
export const GET_ALL_NEWS_SUCCESS =  "GET_ALL_NEWS_SUCCESS"
export const GET_ALL_NEWS_FAIL =  "GET_ALL_NEWS_FAIL"
export const GET_ALL_NEWS_RESET =  "GET_ALL_NEWS_RESET"

export const GET_ALL_IMAGES_REQUEST =  "GET_ALL_IMAGES_REQUEST"
export const GET_ALL_IMAGES_SUCCESS =  "GET_ALL_IMAGES_SUCCESS"
export const GET_ALL_IMAGES_FAIL =  "GET_ALL_IMAGES_FAIL"
export const GET_ALL_IMAGES_RESET =  "GET_ALL_IMAGES_RESET"

export const GET_CALENDAR_REQUEST =  "GET_CALENDAR_REQUEST"
export const GET_CALENDAR_SUCCESS =  "GET_CALENDAR_SUCCESS"
export const GET_CALENDAR_FAIL =  "GET_CALENDAR_FAIL"
export const GET_CALENDAR_RESET =  "GET_CALENDAR_RESET"

export const GET_SESSION_REQUEST =  "GET_SESSION_REQUEST"
export const GET_SESSION_SUCCESS =  "GET_SESSION_SUCCESS"
export const GET_SESSION_FAIL =  "GET_SESSION_FAIL"
export const GET_SESSION_RESET =  "GET_SESSION_RESET"

export const GET_STE_REQUEST =  "GET_STE_REQUEST"
export const GET_STE_SUCCESS =  "GET_STE_SUCCESS"
export const GET_STE_FAIL =  "GET_STE_FAIL"
export const GET_STE_RESET =  "GET_STE_RESET"

export const GET_CLASSTEACHER_REQUEST =  "GET_CLASSTEACHER_REQUEST"
export const GET_CLASSTEACHER_SUCCESS =  "GET_CLASSTEACHER_SUCCESS"
export const GET_CLASSTEACHER_FAIL =  "GET_CLASSTEACHER_FAIL"
export const GET_CLASSTEACHER_RESET =  "GET_CLASSTEACHER_RESET"

export const GET_MAIN_CALENDAR_REQUEST =  "GET_MAIN_CALENDAR_REQUEST"
export const GET_MAIN_CALENDAR_SUCCESS =  "GET_MAIN_CALENDAR_SUCCESS"
export const GET_MAIN_CALENDAR_FAIL =  "GET_MAIN_CALENDAR_FAIL"
export const GET_MAIN_CALENDAR_RESET =  "GET_MAIN_CALENDAR_RESET"

export const GET_PAYMENT_REQUEST =  "GET_PAYMENT_REQUEST"
export const GET_PAYMENT_SUCCESS =  "GET_PAYMENT_SUCCESS"
export const GET_PAYMENT_FAIL =  "GET_PAYMENT_FAIL"
export const GET_PAYMENT_RESET =  "GET_PAYMENT_RESET"

export const GET_ALL_REQUEST =  "GET_ALL_REQUEST"
export const GET_ALL_SUCCESS =  "GET_ALL_SUCCESS"
export const GET_ALL_FAIL =  "GET_ALL_FAIL"
export const GET_ALL_RESET =  "GET_ALL_RESET"

export const GET_ASSIGNMENTS_REQUEST =  "GET_ASSIGNMENTS_REQUEST"
export const GET_ASSIGNMENTS_SUCCESS =  "GET_ASSIGNMENTS_SUCCESS"
export const GET_ASSIGNMENTS_FAIL =  "GET_ASSIGNMENTS_FAIL"
export const GET_ASSIGNMENTS_RESET =  "GET_ASSIGNMENTS_RESET"

export const REC_ASSIGNMENTS_REQUEST =  "REC_ASSIGNMENTS_REQUEST"
export const REC_ASSIGNMENTS_SUCCESS =  "REC_ASSIGNMENTS_SUCCESS"
export const REC_ASSIGNMENTS_FAIL =  "REC_ASSIGNMENTS_FAIL"
export const REC_ASSIGNMENTS_RESET =  "REC_ASSIGNMENTS_RESET"

export const GET_CA_REQUEST =  "GET_CA_REQUEST"
export const GET_CA_SUCCESS =  "GET_CA_SUCCESS"
export const GET_CA_FAIL =  "GET_CA_FAIL"
export const GET_CA_RESET =  "GET_CA_RESET"

export const REC_CA_REQUEST =  "REC_CA_REQUEST"
export const REC_CA_SUCCESS =  "REC_CA_SUCCESS"
export const REC_CA_FAIL =  "REC_CA_FAIL"
export const REC_CA_RESET =  "REC_CA_RESET"

export const GET_EXAM_REQUEST =  "GET_EXAM_REQUEST"
export const GET_EXAM_SUCCESS =  "GET_EXAM_SUCCESS"
export const GET_EXAM_FAIL =  "GET_EXAM_FAIL"
export const GET_EXAM_RESET =  "GET_EXAM_RESET"

export const REC_EXAM_REQUEST =  "REC_EXAM_REQUEST"
export const REC_EXAM_SUCCESS =  "REC_EXAM_SUCCESS"
export const REC_EXAM_FAIL =  "REC_EXAM_FAIL"
export const REC_EXAM_RESET =  "REC_EXAM_RESET"

export const GET_BROADSHEET_REQUEST =  "GET_BROADSHEET_REQUEST"
export const GET_BROADSHEET_SUCCESS =  "GET_BROADSHEET_SUCCESS"
export const GET_BROADSHEET_FAIL =  "GET_BROADSHEET_FAIL"
export const GET_BROADSHEET_RESET =  "GET_BROADSHEET_RESET"

export const MAKE_PAYMENT_REQUEST =  "MAKE_PAYMENT_REQUEST"
export const MAKE_PAYMENT_SUCCESS =  "MAKE_PAYMENT_SUCCESS"
export const MAKE_PAYMENT_FAIL =  "MAKE_PAYMENT_FAIL"
export const MAKE_PAYMENT_RESET =  "MAKE_PAYMENT_RESET"

export const DELETE_PAYMENT_REQUEST =  "DELETE_PAYMENT_REQUEST"
export const DELETE_PAYMENT_SUCCESS =  "DELETE_PAYMENT_SUCCESS"
export const DELETE_PAYMENT_FAIL =  "DELETE_PAYMENT_FAIL"
export const DELETE_PAYMENT_RESET =  "DELETE_PAYMENT_RESET"

export const GET_ALL_SESSION_REQUEST =  "GET_ALL_SESSION_REQUEST"
export const GET_ALL_SESSION_SUCCESS =  "GET_ALL_SESSION_SUCCESS"
export const GET_ALL_SESSION_FAIL =  "GET_ALL_SESSION_FAIL"
export const GET_ALL_SESSION_RESET =  "GET_ALL_SESSION_RESET"

export const GET_BY_CLASS_REQUEST =  "GET_BY_CLASS_REQUEST"
export const GET_BY_CLASS_SUCCESS =  "GET_BY_CLASS_SUCCESS"
export const GET_BY_CLASS_FAIL =  "GET_BY_CLASS_FAIL"
export const GET_BY_CLASS_RESET =  "GET_BY_CLASS_RESET"

export const GET_SELF_REQUEST =  "GET_SELF_REQUEST"
export const GET_SELF_SUCCESS =  "GET_SELF_SUCCESS"
export const GET_SELF_FAIL =  "GET_SELF_FAIL"
export const GET_SELF_RESET =  "GET_SELF_RESET"

export const UPDATE_FEE_REQUEST =  "UPDATE_FEE_REQUEST"
export const UPDATE_FEE_SUCCESS =  "UPDATE_FEE_SUCCESS"
export const UPDATE_FEE_FAIL =  "UPDATE_FEE_FAIL"
export const UPDATE_FEE_RESET =  "UPDATE_FEE_RESET"

export const UPDATE_PAID_REQUEST =  "UPDATE_PAID_REQUEST"
export const UPDATE_PAID_SUCCESS =  "UPDATE_PAID_SUCCESS"
export const UPDATE_PAID_FAIL =  "UPDATE_PAID_FAIL"
export const UPDATE_PAID_RESET =  "UPDATE_PAID_RESET"

export const GET_SINGLE_TEACHER_REQUEST =  "GET_SINGLE_TEACHER_REQUEST"
export const GET_SINGLE_TEACHER_SUCCESS =  "GET_SINGLE_TEACHER_SUCCESS"
export const GET_SINGLE_TEACHER_FAIL =  "GET_SINGLE_TEACHER_FAIL"
export const GET_SINGLE_TEACHER_RESET =  "GET_SINGLE_TEACHER_RESET"

export const TEACHER_GET_STUDENTS_REQUEST =  "TEACHER_GET_STUDENTS_REQUEST"
export const TEACHER_GET_STUDENTS_SUCCESS =  "TEACHER_GET_STUDENTS_SUCCESS"
export const TEACHER_GET_STUDENTS_FAIL =  "TEACHER_GET_STUDENTS_FAIL"
export const TEACHER_GET_STUDENTS_RESET =  "TEACHER_GET_STUDENTS_RESET"

export const TEACHER_GET_RESULTS_REQUEST =  "TEACHER_GET_RESULTS_REQUEST"
export const TEACHER_GET_RESULTS_SUCCESS =  "TEACHER_GET_RESULTS_SUCCESS"
export const TEACHER_GET_RESULTS_FAIL =  "TEACHER_GET_RESULTS_FAIL"
export const TEACHER_GET_RESULTS_RESET =  "TEACHER_GET_RESULTS_RESET"

export const ADMIN_GET_RESULTS_REQUEST =  "ADMIN_GET_RESULTS_REQUEST"
export const ADMIN_GET_RESULTS_SUCCESS =  "ADMIN_GET_RESULTS_SUCCESS"
export const ADMIN_GET_RESULTS_FAIL =  "ADMIN_GET_RESULTS_FAIL"
export const ADMIN_GET_RESULTS_RESET =  "ADMIN_GET_RESULTS_RESET"

export const STUDENT_GET_RESULTS_REQUEST =  "STUDENT_GET_RESULTS_REQUEST"
export const STUDENT_GET_RESULTS_SUCCESS =  "STUDENT_GET_RESULTS_SUCCESS"
export const STUDENT_GET_RESULTS_FAIL =  "STUDENT_GET_RESULTS_FAIL"
export const STUDENT_GET_RESULTS_RESET =  "STUDENT_GET_RESULTS_RESET"

export const PARENT_GET_ATTENDANCE_REQUEST =  "PARENT_GET_ATTENDANCE_REQUEST"
export const PARENT_GET_ATTENDANCE_SUCCESS =  "PARENT_GET_ATTENDANCE_SUCCESS"
export const PARENT_GET_ATTENDANCE_FAIL =  "PARENT_GET_ATTENDANCE_FAIL"
export const PARENT_GET_ATTENDANCE_RESET =  "PARENT_GET_ATTENDANCE_RESET"

export const TEACHER_UPDATE_PASSWORD_REQUEST =  "TEACHER_UPDATE_PASSWORD_REQUEST"
export const TEACHER_UPDATE_PASSWORD_SUCCESS =  "TEACHER_UPDATE_PASSWORD_SUCCESS"
export const TEACHER_UPDATE_PASSWORD_FAIL =  "TEACHER_UPDATE_PASSWORD_FAIL"
export const TEACHER_UPDATE_PASSWORD_RESET =  "TEACHER_UPDATE_PASSWORD_RESET"

export const STUDENT_UPDATE_PASSWORD_REQUEST =  "STUDENT_UPDATE_PASSWORD_REQUEST"
export const STUDENT_UPDATE_PASSWORD_SUCCESS =  "STUDENT_UPDATE_PASSWORD_SUCCESS"
export const STUDENT_UPDATE_PASSWORD_FAIL =  "STUDENT_UPDATE_PASSWORD_FAIL"
export const STUDENT_UPDATE_PASSWORD_RESET =  "STUDENT_UPDATE_PASSWORD_RESET"

export const PARENT_UPDATE_PASSWORD_REQUEST =  "PARENT_UPDATE_PASSWORD_REQUEST"
export const PARENT_UPDATE_PASSWORD_SUCCESS =  "PARENT_UPDATE_PASSWORD_SUCCESS"
export const PARENT_UPDATE_PASSWORD_FAIL =  "PARENT_UPDATE_PASSWORD_FAIL"
export const PARENT_UPDATE_PASSWORD_RESET =  "PARENT_UPDATE_PASSWORD_RESET"

export const TEACHER_SIGN_UP_REQUEST =  "TEACHER_SIGN_UP_REQUEST"
export const TEACHER_SIGN_UP_SUCCESS =  "TEACHER_SIGN_UP_SUCCESS"
export const TEACHER_SIGN_UP_FAIL =  "TEACHER_SIGN_UP_FAIL"
export const TEACHER_SIGN_UP_RESET =  "TEACHER_SIGN_UP_RESET"

export const STUDENT_SIGN_UP_REQUEST =  "STUDENT_SIGN_UP_REQUEST"
export const STUDENT_SIGN_UP_SUCCESS =  "STUDENT_SIGN_UP_SUCCESS"
export const STUDENT_SIGN_UP_FAIL =  "STUDENT_SIGN_UP_FAIL"
export const STUDENT_SIGN_UP_RESET =  "STUDENT_SIGN_UP_RESET"

export const PARENT_SIGN_UP_REQUEST =  "PARENT_SIGN_UP_REQUEST"
export const PARENT_SIGN_UP_SUCCESS =  "PARENT_SIGN_UP_SUCCESS"
export const PARENT_SIGN_UP_FAIL =  "PARENT_SIGN_UP_FAIL"
export const PARENT_SIGN_UP_RESET =  "PARENT_SIGN_UP_RESET"

export const ADMIN_SIGN_UP_REQUEST =  "ADMIN_SIGN_UP_REQUEST"
export const ADMIN_SIGN_UP_SUCCESS =  "ADMIN_SIGN_UP_SUCCESS"
export const ADMIN_SIGN_UP_FAIL =  "ADMIN_SIGN_UP_FAIL"
export const ADMIN_SIGN_UP_RESET =  "ADMIN_SIGN_UP_RESET"

export const POST_NEWS_REQUEST =  "POST_NEWS_REQUEST"
export const POST_NEWS_SUCCESS =  "POST_NEWS_SUCCESS"
export const POST_NEWS_FAIL =  "POST_NEWS_FAIL"
export const POST_NEWS_RESET =  "POST_NEWS_RESET"

export const POST_SESSION_REQUEST =  "POST_SESSION_REQUEST"
export const POST_SESSION_SUCCESS =  "POST_SESSION_SUCCESS"
export const POST_SESSION_FAIL =  "POST_SESSION_FAIL"
export const POST_SESSION_RESET =  "POST_SESSION_RESET"

export const POST_TERM_REQUEST =  "POST_TERM_REQUEST"
export const POST_TERM_SUCCESS =  "POST_TERM_SUCCESS"
export const POST_TERM_FAIL =  "POST_TERM_FAIL"
export const POST_TERM_RESET =  "POST_TERM_RESET"

export const POST_EVENT_REQUEST =  "POST_EVENT_REQUEST"
export const POST_EVENT_SUCCESS =  "POST_EVENT_SUCCESS"
export const POST_EVENT_FAIL =  "POST_EVENT_FAIL"
export const POST_EVENT_RESET =  "POST_EVENT_RESET"

export const POST_SUB_REQUEST =  "POST_SUB_REQUEST"
export const POST_SUB_SUCCESS =  "POST_SUB_SUCCESS"
export const POST_SUB_FAIL =  "POST_SUB_FAIL"
export const POST_SUB_RESET =  "POST_SUB_RESET"

export const POST_ASSIGNMENT_REQUEST =  "POST_ASSIGNMENT_REQUEST"
export const POST_ASSIGNMENT_SUCCESS =  "POST_ASSIGNMENT_SUCCESS"
export const POST_ASSIGNMENT_FAIL =  "POST_ASSIGNMENT_FAIL"
export const POST_ASSIGNMENT_RESET =  "POST_ASSIGNMENT_RESET"

export const POST_EXAM_REQUEST =  "POST_EXAM_REQUEST"
export const POST_EXAM_SUCCESS =  "POST_EXAM_SUCCESS"
export const POST_EXAM_FAIL =  "POST_EXAM_FAIL"
export const POST_EXAM_RESET =  "POST_EXAM_RESET"

export const POST_CA_REQUEST =  "POST_CA_REQUEST"
export const POST_CA_SUCCESS =  "POST_CA_SUCCESS"
export const POST_CA_FAIL =  "POST_CA_FAIL"
export const POST_CA_RESET =  "POST_CA_RESET"

export const POST_RESULT_REQUEST =  "POST_RESULT_REQUEST"
export const POST_RESULT_SUCCESS =  "POST_RESULT_SUCCESS"
export const POST_RESULT_FAIL =  "POST_RESULT_FAIL"
export const POST_RESULT_RESET =  "POST_RESULT_RESET"

export const POST_ATTENDANCE_REQUEST =  "POST_ATTENDANCE_REQUEST"
export const POST_ATTENDANCE_SUCCESS =  "POST_ATTENDANCE_SUCCESS"
export const POST_ATTENDANCE_FAIL =  "POST_ATTENDANCE_FAIL"
export const POST_ATTENDANCE_RESET =  "POST_ATTENDANCE_RESET"

export const POST_IMAGE_REQUEST =  "POST_IMAGE_REQUEST"
export const POST_IMAGE_SUCCESS =  "POST_IMAGE_SUCCESS"
export const POST_IMAGE_FAIL =  "POST_IMAGE_FAIL"
export const POST_IMAGE_RESET =  "POST_IMAGE_RESET"

export const CONTACT_US_REQUEST =  "CONTACT_US_REQUEST"
export const CONTACT_US_SUCCESS =  "CONTACT_US_SUCCESS"
export const CONTACT_US_FAIL =  "CONTACT_US_FAIL"
export const CONTACT_US_RESET =  "CONTACT_US_RESET"

export const TEACHER_AUTH_REQUEST = "TEACHER_AUTH_REQUEST";
export const TEACHER_AUTH_SUCCESS = "TEACHER_AUTH_SUCCESS";
export const TEACHER_AUTH_FAIL = "TEACHER_AUTH_FAIL";
export const TEACHER_AUTH_LOGOUT = "TEACHER_AUTH_LOGOUT";

export const PARENT_AUTH_REQUEST = "PARENT_AUTH_REQUEST";
export const PARENT_AUTH_SUCCESS = "PARENT_AUTH_SUCCESS";
export const PARENT_AUTH_FAIL = "PARENT_AUTH_FAIL";
export const PARENT_AUTH_LOGOUT = "PARENT_AUTH_LOGOUT";

export const ADMIN_AUTH_REQUEST = "ADMIN_AUTH_REQUEST";
export const ADMIN_AUTH_SUCCESS = "ADMIN_AUTH_SUCCESS";
export const ADMIN_AUTH_FAIL = "ADMIN_AUTH_FAIL";
export const ADMIN_AUTH_LOGOUT = "ADMIN_AUTH_LOGOUT";

export const STUDENT_AUTH_REQUEST = "STUDENT_AUTH_REQUEST";
export const STUDENT_AUTH_SUCCESS = "STUDENT_AUTH_SUCCESS";
export const STUDENT_AUTH_FAIL = "STUDENT_AUTH_FAIL";
export const STUDENT_AUTH_LOGOUT = "STUDENT_AUTH_LOGOUT";

export const DELETE_SINGLE_TEACHER_REQUEST =  "DELETE_SINGLE_TEACHER_REQUEST"
export const DELETE_SINGLE_TEACHER_SUCCESS =  "DELETE_SINGLE_TEACHER_SUCCESS"
export const DELETE_SINGLE_TEACHER_FAIL =  "DELETE_SINGLE_TEACHER_FAIL"

export const DELETE_SINGLE_PARENT_REQUEST =  "DELETE_SINGLE_PARENT_REQUEST"
export const DELETE_SINGLE_PARENT_SUCCESS =  "DELETE_SINGLE_PARENT_SUCCESS"
export const DELETE_SINGLE_PARENT_FAIL =  "DELETE_SINGLE_PARENT_FAIL"

export const DELETE_SINGLE_STUDENT_REQUEST =  "DELETE_SINGLE_STUDENT_REQUEST"
export const DELETE_SINGLE_STUDENT_SUCCESS =  "DELETE_SINGLE_STUDENT_SUCCESS"
export const DELETE_SINGLE_STUDENT_FAIL =  "DELETE_SINGLE_STUDENT_FAIL"

export const DELETE_SINGLE_NEWS_REQUEST =  "DELETE_SINGLE_NEWS_REQUEST"
export const DELETE_SINGLE_NEWS_SUCCESS =  "DELETE_SINGLE_NEWS_SUCCESS"
export const DELETE_SINGLE_NEWS_FAIL =  "DELETE_SINGLE_NEWS_FAIL"

export const DELETE_SINGLE_IMAGE_REQUEST =  "DELETE_SINGLE_IMAGE_REQUEST"
export const DELETE_SINGLE_IMAGE_SUCCESS =  "DELETE_SINGLE_IMAGE_SUCCESS"
export const DELETE_SINGLE_IMAGE_FAIL =  "DELETE_SINGLE_IMAGE_FAIL"

export const DELETE_SINGLE_RESULT_REQUEST =  "DELETE_SINGLE_RESULT_REQUEST"
export const DELETE_SINGLE_RESULT_SUCCESS =  "DELETE_SINGLE_RESULT_SUCCESS"
export const DELETE_SINGLE_RESULT_FAIL =  "DELETE_SINGLE_RESULT_FAIL"

export const DELETE_SINGLE_SESSION_REQUEST =  "DELETE_SINGLE_SESSION_REQUEST"
export const DELETE_SINGLE_SESSION_SUCCESS =  "DELETE_SINGLE_SESSION_SUCCESS"
export const DELETE_SINGLE_SESSION_FAIL =  "DELETE_SINGLE_SESSION_FAIL"

export const DELETE_SINGLE_TERM_REQUEST =  "DELETE_SINGLE_TERM_REQUEST"
export const DELETE_SINGLE_TERM_SUCCESS =  "DELETE_SINGLE_TERM_SUCCESS"
export const DELETE_SINGLE_TERM_FAIL =  "DELETE_SINGLE_TERM_FAIL"

export const DELETE_SINGLE_EVENT_REQUEST =  "DELETE_SINGLE_EVENT_REQUEST"
export const DELETE_SINGLE_EVENT_SUCCESS =  "DELETE_SINGLE_EVENT_SUCCESS"
export const DELETE_SINGLE_EVENT_FAIL =  "DELETE_SINGLE_EVENT_FAIL"