import { combineReducers } from "redux";
import { getAllTeachersReducer, getClassteacherReducer, getSingleTeacherReducer, postAssignmentReducer, postAttendanceReducer, postCaReducer, postExamReducer, postResultReducer, searchTeachersReducer, studentGetResultsReducer, teacherAuthReducer, teacherGetResultsReducer, teacherGetStudentsReducer, teacherRegisterReducer, teacherUpdatePasswordReducer } from "./Teacherreducer";
import { contactUsReducer, postSubReducer } from "./Contactreducer";
import { getAllSessionReducer, getMainCalendarReducer, getSTEReducer, postEventReducer, postSessionReducer, postTermReducer, searchCalendarReducer } from "./CalendarReducer";
import { getAllNewsReducer, postNewsReducer } from "./NewsReducer";
import { getAllImagesReducer, postImageReducer } from "./GalleryReducer";
import { adminAuthReducer, adminGetAllParentsReducer, adminGetAllStudentsReducer, adminGetAllTeachersReducer, adminGetResultsReducer, adminRegisterReducer, adminSearchImagesReducer, adminSearchNewsReducer, adminSearchParentsReducer, adminSearchStudentsReducer, adminSearchTeachersReducer, eventDeleteReducer, getAllClassesReducer, getAllDepartmentsReducer, getAllPostsReducer, getAllReducer, getAllSubjectsReducer, getBroadsheetReducer, getByClassReducer, getPaymentReducer, imageDeleteReducer, makePaymentReducer, newsDeleteReducer, parentDeleteReducer, parentRegisterReducer, paymentDeleteReducer, resultDeleteReducer, sessionDeleteReducer, studentDeleteReducer, studentRegisterReducer, teacherDeleteReducer, termDeleteReducer, updateClassReducer, updateFeeReducer, updatePaidReducer } from "./AdminReducer";
import { getAssignmentReducer, getCaReducer, getExamReducer, getSelfReducer, recAssignmentReducer, recCaReducer, recExamReducer, studentAuthReducer, studentUpdatePasswordReducer } from "./StudentReducer";
import { parentAuthReducer, parentGetAttendanceReducer, parentUpdatePasswordReducer } from "./ParentReducer";

const rootReducer = combineReducers({
    getAllTeachers: getAllTeachersReducer,
    getSingleTeacher: getSingleTeacherReducer,
    contactUs: contactUsReducer,
    teacherRegister: teacherRegisterReducer,
    postNews: postNewsReducer,
    getAllNews: getAllNewsReducer,
    postImage: postImageReducer,
    getAllImages: getAllImagesReducer,
    postSub: postSubReducer,
    searchTeachers: searchTeachersReducer,
    teacherAuth: teacherAuthReducer,
    adminRegister: adminRegisterReducer,
    adminAuth: adminAuthReducer,
    adminGetAllTeachers: adminGetAllTeachersReducer,
    adminSearchTeachers: adminSearchTeachersReducer,
    getAllSubjects: getAllSubjectsReducer,
    getAllPosts: getAllPostsReducer,
    getAllClasses: getAllClassesReducer,
    getAllDepartments: getAllDepartmentsReducer,
    adminGetAllStudents: adminGetAllStudentsReducer,
    adminSearchStudents: adminSearchStudentsReducer,
    studentRegister: studentRegisterReducer,
    adminSearchNews: adminSearchNewsReducer,
    adminSearchImages: adminSearchImagesReducer,
    postSession: postSessionReducer,
    getAllSession: getAllSessionReducer,
    postTerm: postTermReducer,
    postEvent: postEventReducer,
    getSTE: getSTEReducer,
    searchCalendar: searchCalendarReducer,
    teacherGetStudents: teacherGetStudentsReducer,
    postResult: postResultReducer,
    teacherGetResults: teacherGetResultsReducer,
    teacherUpdatePassword: teacherUpdatePasswordReducer,
    studentAuth: studentAuthReducer,
    studentGetResults: studentGetResultsReducer,
    studentUpdatePassword: studentUpdatePasswordReducer,
    getMainCalendar: getMainCalendarReducer,
    adminGetResults: adminGetResultsReducer,
    termDelete: termDeleteReducer,
    sessionDelete: sessionDeleteReducer,
    imageDelete: imageDeleteReducer,
    newsDelete: newsDeleteReducer,
    eventDelete: eventDeleteReducer,
    resultDelete: resultDeleteReducer,
    teacherDelete: teacherDeleteReducer,
    studentDelete: studentDeleteReducer,
    getClassteacher: getClassteacherReducer,
    postAttendance: postAttendanceReducer,
    parentAuth: parentAuthReducer,
    parentRegister: parentRegisterReducer,
    adminGetAllParents: adminGetAllParentsReducer,
    adminSearchParents: adminSearchParentsReducer,
    parentDelete: parentDeleteReducer,
    parentGetAttendance: parentGetAttendanceReducer,
    parentUpdatePassword: parentUpdatePasswordReducer,
    paymentDelete: paymentDeleteReducer,
    getPayment: getPaymentReducer,
    makePayment: makePaymentReducer,
    getAll: getAllReducer,
    getBroadsheet: getBroadsheetReducer,
    postAssignment: postAssignmentReducer,
    postExam: postExamReducer,
    postCa: postCaReducer,
    getAssignment: getAssignmentReducer,
    recAssignment: recAssignmentReducer,
    getCa: getCaReducer,
    recCa: recCaReducer,
    getExam: getExamReducer,
    recExam: recExamReducer,
    updateFee: updateFeeReducer,
    getByClass: getByClassReducer,
    updatePaid: updatePaidReducer,
    getSelf: getSelfReducer,
    updateClass: updateClassReducer
})
export {rootReducer}